[centos] Handle PIDFILE more precisely

diff --git a/data/init.d/centos/generate_hap2_init_file.sh.in b/data/init.d/centos/generate_hap2_init_file.sh.in
--- a/data/init.d/centos/generate_hap2_init_file.sh.in
+++ b/data/init.d/centos/generate_hap2_init_file.sh.in
@@ -40,11 +40,17 @@ start() {
 }
 
 stop() {
-	echo -n \$"Stopping \$PROGNAME: "
-	RETVAL=$?
-	kill -s 15 \`cat \${PIDFILE}\`
-	echo
-	[ \$RETVAL -eq 0 ] && rm -f \$LOCKFILE
+	echo -n $"Stopping $PROGNAME: "
+	RETVAL=0
+	if [ -f $PIDFILE ]; then
+		kill -s 15 `cat ${PIDFILE}`
+		rm -f $LOCKFILE
+		RETVAL=$?
+		echo
+		[ $RETVAL -eq 0 ] && rm $PIDFILE
+	else
+		printf "%s\n" "pidfile not found"
+	fi
 }
 
 RETVAL=0
@@ -60,7 +66,17 @@ case "\$1" in
 		start
 		;;
 	status)
-		status \$NAME
+		printf "%-50s" "Checking \$NAME..."
+		if [ -f \$PIDFILE ]; then
+			PID=\`cat \$PIDFILE\`
+			if [ -z "\`ps axf | grep \${PID} | grep -v grep\`" ]; then
+				printf "%s\n" "Process dead but pidfile exists"
+			else
+				echo "Running"
+			fi
+		else
+			printf "%s\n" "Service not running"
+		fi
 		;;
 	*)
 		echo \$"Usage: \$PROGNAME {start|stop|restart|status}" >&2
